config/routes.rb
Rails.application.routes.draw do

  get "/up", to: proc { [200, { "Content-Type" => "text/plain" }, ["OK"]] }
  get "/privacy", to: "static_pages#privacy", as: :privacy

  resources :ogp_templates, only: [:show]

  resources :omikujis, only: %i[index create] do
    collection do
      post :reset
    end
  end

  resource :modal, only: [:show, :create, :destroy]

  namespace :internal do
    post "ogp_upload", to: "ogp_images#create"
  end

  root "tops#index"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/my_history.rb
class MyHistory < ApplicationRecord
  belongs_to :snake

  scope :recent, -> { order(created_at: :desc).limit(5) }

  after_create_commit :generate_ogp

  private

  def generate_ogp
    Rails.logger.info("📄 MyHistory作成: Snake##{snake_id} の OGP生成ジョブをキューに追加")
    GenerateOgpJob.perform_later(snake_id)
  end
end

app/models/omikuji_history.rb
class OmikujiHistory < ApplicationRecord
  belongs_to :snake

  has_one_attached :image

  scope :recent, -> { order(created_at: :desc).limit(10) }


  broadcasts_to ->(_) { "public-history" },
  inserts_by: :prepend,
  target: "public-history-list",
  partial: "omikujis/history_item"
end

app/models/omikuji_result.rb
class OmikujiResult < ApplicationRecord
  has_many :snakes, dependent: :destroy
end

app/models/snake.rb
class Snake < ApplicationRecord
  belongs_to :omikuji_result
  has_many :snake_colors, dependent: :destroy

  def self.random_snake
    includes(:omikuji_result, :snake_colors).order("RANDOM()").first
  end

  has_one_attached :image
end

app/models/snake_color.rb
class SnakeColor < ApplicationRecord
  belongs_to :snake
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/internal/ogp_images_controller.rb
class Internal::OgpImagesController < ApplicationController
  protect_from_forgery with: :null_session

  def create
    snake = ::Snake.find_by(id: params[:id])

    unless snake
      render json: { error: "Snake not found" }, status: :not_found and return
    end

    if params[:image].respond_to?(:tempfile)
      snake.image.detach if snake.image.attached?

      snake.image.attach(
        io: params[:image].tempfile,
        filename: "ogp_#{SecureRandom.hex(6)}.png",
        content_type: params[:image].content_type
      )

      public_url = "https://pub-1907a15a98994ec0915c588d7425f466.r2.dev/#{snake.image.key}"

      render json: { url: public_url }, status: :ok
    else
      render json: { error: "No image provided" }, status: :bad_request
    end
  end
end

app/controllers/modals_controller.rb
class ModalsController < ApplicationController

  def create
    @css_class = ["style-red", "style-blue", "style-green"].sample
  end

  def destroy
    @saved_histories = OmikujiHistory.recent
  end
end

app/controllers/ogp_templates_controller.rb
class OgpTemplatesController < ApplicationController
  def show
    @snake = Snake.find_by(id: params[:id]) || Snake.first # nil回避
  end
end

app/controllers/omikujis_controller.rb
class OmikujisController < ApplicationController
  before_action :set_saved_histories, only: %i[index create reset]

  def index
  end

  def create
    @snake = Snake.random_snake
    session[:snake_id] = @snake.id

    @history = OmikujiHistory.create!(snake: @snake)

    # MyHistoryを更新
    MyHistory.create!(snake: @snake)
    my_history_count = MyHistory.count
    if my_history_count > 5
      MyHistory.order(created_at: :asc).limit(my_history_count - 5).destroy_all
    end

    @saved_histories = OmikujiHistory.recent
    @my_histories = MyHistory.recent

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path, notice: "#{@snake.name} が選ばれました！" }
    end
  end

  def reset
    session.delete(:snake_id)

    OmikujiHistory.delete_all
    MyHistory.delete_all

    @saved_histories = []
    @my_histories = []

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path, notice: "履歴をリセットしました！" }
    end
  end

  private

  def set_saved_histories
    @saved_histories = OmikujiHistory.recent
    @my_histories = MyHistory.recent
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def privacy
    render layout: false if turbo_frame_request?
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @saved_histories = OmikujiHistory.recent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/internal/ogp_images_helper.rb
module Internal::OgpImagesHelper
end

app/helpers/modals_helper.rb
module ModalsHelper
end

app/helpers/ogp_templates_helper.rb
module OgpTemplatesHelper
end

app/helpers/omikujis_helper.rb
module OmikujisHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "おみくじ(巳)" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="turbo-refresh-method" content="morph">
    <meta name="turbo-refresh-scroll" content="preserve">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% og_image_url = URI.join(root_url, asset_path("ogp.png")) %>

    <meta property="og:title" content="おみくじ(巳)" />
    <meta property="og:description" content="運勢を引いて、今日の気分を知ろう！" />
    <meta property="og:image" content="<%= og_image_url %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://omikuji.fly.dev/" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="おみくじ(巳)" />
    <meta name="twitter:description" content="運勢を引いて、今日の気分を知ろう！" />
    <meta name="twitter:image" content="<%= og_image_url %>" />

    <% if @snake&.image&.attached? %>
      <meta property="og:title" content="今日の運勢は『<%= @snake.omikuji_result.name %>』" />
      <meta property="og:description" content="<%= @snake.omikuji_result.description %>" />
      <meta property="og:image" content="https://pub-1907a15a98994ec0915c588d7425f466.r2.dev/<%= @snake.image.key %>" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="<%= request.original_url %>" />

      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="今日の運勢は『<%= @snake.omikuji_result.name %>』" />
      <meta name="twitter:description" content="<%= @snake.omikuji_result.description %>" />
      <meta name="twitter:image" content="https://pub-1907a15a98994ec0915c588d7425f466.r2.dev/<%= @snake.image.key %>" />
    <% end %>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-J8KRKRHTGF"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-J8KRKRHTGF');
    </script>


    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/modals/_modal.html.erb
<div id="omikuji-result">
  <div id="modal" class="modal is-active">
    <div class="modal-background"></div>

    <div class="modal-wrapper">
      <h2 class="floating-message">おみくじの中から1つ選んでください！</h2>

    <div class="modal-content">
      <%= button_to "×", modal_path, method: :delete, data: { turbo_frame: "modal" }, class: "modal-close-button" %>
      <div class="omikuji-container">
        <% 5.times do %>
          <%= render "omikujis/pull" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/modals/create.turbo_stream.erb
<%= turbo_stream.replace "modal" do %>
  <%= render "modals/modal", css_class: @css_class %>
<% end %>

app/views/modals/destroy.turbo_stream.erb
<%= turbo_stream.remove "modal" %>

<%= turbo_stream.append "modal-open" do %>
    <%= render "tops/welcome" %>
<% end %>

app/views/ogp_templates/show.html.erb
<%= turbo_frame_tag "omikuji-result", data: { controller: "omikuji" } do %>
  <div class="fortune-effect-container" data-leaf-result="<%= @snake&.omikuji_result&.name %>"></div>
  <h2 class="sub-title">おみくじ結果</h2>
  <div class="container">
    <% if @snake %>
      <%= render "omikujis/result" %>
      <%= render "omikujis/snake" %>
    <% else %>
      <p>蛇のデータがありません。</p>
    <% end %>
  </div>
<% end %>

app/views/omikujis/_display.html.erb
<%= turbo_frame_tag "omikuji-result", data: { controller: "omikuji" } do %>
  <div class="fortune-effect-container" data-leaf-result="<%= @snake&.omikuji_result&.name %>"></div>
  <h2 class="sub-title">おみくじ結果</h2>
  <div class="container">
    <% if @snake %>
      <%= render "omikujis/ogp" %>
      <div class ="bottom">
        <%= render "omikujis/result" %>
      </div>
      <%= render "omikujis/snake" %>
    <% else %>
      <p>蛇のデータがありません。</p>
    <% end %>
    <%= render "omikujis/pull" %>
  </div>
  <%= render "omikujis/my_history_list" %>
  <%= render "tops/home" %>
<% end %>

app/views/omikujis/_histories.html.erb
<h2>履歴（最大3件）</h2>
<% if @saved_histories.any? %>
  <ul>
    <% @saved_histories.each do |history| %>
      <li>
        <strong><%= history.snake.omikuji_result.name %></strong>:
        <%= history.snake.omikuji_result.description %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>保存された履歴がありません。</p>
<% end %>

app/views/omikujis/_history_item.html.erb
<% history = local_assigns[:omikuji_history] %>
<p id="<%= dom_id(history) %>" class="omikuji-item">
    <strong class="omikuji-result"><%= history.snake.omikuji_result.name %></strong><br>
    <span class="omikuji-description"><%= history.snake.omikuji_result.description %></span><br>
    <span class="omikuji-date"><%= history.created_at.strftime('%Y-%m-%d %H:%M') %></span>
</p>

app/views/omikujis/_my_history_list.html.erb
<div id="my-history-list" class="omikuji-list">
  <% (@my_histories || []).each do |history| %>
    <%= render partial: "omikujis/history_item", locals: { omikuji_history: history } %>
  <% end %>
</div>

app/views/omikujis/_ogp.html.erb
<%= link_to "シェア",
  "https://twitter.com/intent/tweet?" + {
    text: "今日の運勢を占ってみた！\n\n#おみくじ #巳年\n\n",
    url: main_app.ogp_template_url(@snake, static: 1)
  }.to_query,
  target: "_blank",
  rel: "noopener",
  class: "x-button",
  id: "x-share-button"
%>

app/views/omikujis/_public_history_list.html.erb
<div id="public-history-list" class="omikuji-list">
  <% (@saved_histories || []).each do |history| %>
    <%= render partial: "omikujis/history_item", locals: { omikuji_history: history } %>
  <% end %>
</div>

app/views/omikujis/_pull.html.erb
<% if params[:controller] == "modals" %>
  <% button_class = "omikuji-button" %>
  <% button_text = "おみくじ" %>
  <% button_options = {} %>
<% else %>
  <% button_class = "button omikuji-reshuffle" %>
  <% button_text = "おみくじを引き直す" %>
  <% button_options = { id: "reshuffle-button" } %>
<% end %>

<%= button_to omikujis_path, method: :post, data: { turbo_stream: true }, class: button_class, **button_options do %>
  <span class="omikuji-text"><%= button_text %></span>
<% end %>

app/views/omikujis/_reset.html.erb
<%= button_to "履歴を消しますか？", reset_omikujis_path, method: :post, data: { turbo_frame: "result-container" }, class: "button" %>

app/views/omikujis/_result.html.erb
<h1><%= @snake.omikuji_result.name %></h1>
<%= @snake.name %>
<p><%= @snake.omikuji_result.description %></p>

app/views/omikujis/_snake.html.erb
<div class="centered-container">
    <div class="snake bottom">
        <%= render "snake/head" %>
        <%= render "snake/body" %>
        <%= render "snake/tall" %>
    </div>
</div>

app/views/omikujis/create.turbo_stream.erb
<%= turbo_stream.replace "omikuji-result" do %>
  <%= render "omikujis/display", snake: @snake %>
<% end %>

<%= turbo_stream.prepend "public-history-list" do %>
  <%= render partial: "omikujis/history_item", locals: { omikuji_history: @history } %>
<% end %>

app/views/omikujis/index.html.erb
<%= turbo_frame_tag "modal" do %>
<div class="omikuji-container">
  <% 5.times do %>
    <%= render "omikujis/pull" %>
  <%end%>
  </div>
<%end%>

app/views/snake/_body.html.erb
<% (1..4).each do |layer| %>
  <% color_data = @snake.snake_colors.find_by(layer: layer) %>
  <div class="rounded-rectangle layer<%= layer %>"
      style="background-color: <%= color_data&.color %>">
    <% if color_data&.circle %>
      <div class="layer-circle"></div>
    <% end %>
    <% if color_data&.horizontal_line %>
      <div class="layer-horizontal-line"></div>
      <div class="layer-horizontal-line-2"></div>
    <% end %>
    <% if color_data&.vertical_line %>
      <div class="lines-container">
        <div class="layer-vertical-line"></div>
        <div class="layer-vertical-line"></div>
        <div class="layer-vertical-line"></div>
        <div class="layer-vertical-line"></div>
        <div class="layer-vertical-line"></div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/snake/_head.html.erb
<div class="head" style="background-color: <%= @snake.snake_colors.find_by(layer: 1)&.color %>">
  <div class="eye left"></div>
  <div class="eye right"></div>
  <div class="omega"></div>
  <div class="tongue"></div>
</div>

app/views/snake/_tall.html.erb
<div class="tail-container">
  <div class="tail-outer" style="background-color: <%= @snake.snake_colors.find_by(layer: 'tail-outer')&.color %>;">
    <% if @snake.snake_colors.find_by(layer: 'tail-outer')&.horizontal_line %>
      <div class="layer-horizontal-line"></div>
    <% end %>
    <% if @snake.snake_colors.find_by(layer: 'tail-outer')&.vertical_line %>
      <div class="layer-vertical-line"></div>
    <% end %>
  </div>
    <div class="tail-inner">
    <div class="tail-inner-cut">
    </div>
  </div>
</div>

app/views/static_pages/privacy.html.erb
<%= turbo_frame_tag "privacy_modal" do %>
  <div class="wrapper privacy-content">
    <h2>プライバシーポリシー</h2>

    <section>
      <h3>📌 取得する情報</h3>
      <p>当サイトでは、Googleアナリティクスを利用し、Cookieを通じて匿名のアクセス情報を収集しています。</p>
    </section>

    <section>
      <h3>🎯 利用目的</h3>
      <p>アクセス解析によるサイト改善のために使用されます。</p>
    </section>

    <section>
      <h3>🔒 個人情報について</h3>
      <p>当サイトでは、ユーザーの個人情報（名前・メールアドレスなど）は一切取得していません。</p>
    </section>

    <section>
      <h3>✉️ お問い合わせ</h3>
      <p>お問い合わせは、以下のメールアドレスまでご連絡ください。<br><strong>e-mail:</strong> kzkio114@gmail.com</p>
    </section>

    <div class="mt-4">
      <%= render "tops/home" %>
    </div>
  </div>
<% end %>

app/views/tops/_home.html.erb
<% if params[:controller] == "static_pages" %>
  <% button_class = "" %>
  <% button_text = "戻る" %>
<% else %>
  <% button_class = "button top" %>
  <% button_text = "ホームに戻る？" %>
<% end %>

<%= link_to button_text, root_path, class: button_class %>

app/views/tops/_omikuji.html.erb
<%= button_to "おみくじを選ぶ", modal_path, remote: true, data: { turbo_frame: "modal" }, class: "button bottom" %>

app/views/tops/_welcome.html.erb
<div id="modal">
  <div class="bottom-container">
    <h1 class="main-title">ようこそ</h1>
    <h2 class="sub-title">今年の干支おみくじ引きますか？</h2>
  </div>

  <%= render "tops/omikuji" %>

  <h1 class="section-title">みんなの占い結果</h1>
  <%= render partial: "omikujis/public_history_list", locals: { omikuji_history: @history } %>
</div>

app/views/tops/index.html.erb
<%= turbo_frame_tag "privacy_modal" do %>
  <%= turbo_stream_from "public-history" %>
  <div class="wrapper">
    <div class="sound-control">
      <button data-controller="audio" data-action="click->audio#toggle" class="bgm-button">
        静けさをひらく(音を再生/停止)
      </button>
    </div>
    <%= turbo_frame_tag "omikuji-result" do %>
      <div id="modal-open"></div>
        <%= render "tops/welcome" %>
        <div class="top">
        <%= link_to "プライバシーポリシー", privacy_path,
        data: { turbo_frame: "privacy_modal" } %>
        <%= link_to "https://github.com/kzkio114/rails_vanilla",
        class: "top ml",
        style: "display:inline-flex; align-items:center; text-decoration:none; color:#000;" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16" style="margin-right:5px;">
      <path d="M8 0C3.58 0 0 3.58 0 8a8 8 0 0 0 5.47 7.59c.4.07.55-.17.55-.38
      0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13
      -.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07
      -1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.01.08-2.11 0 0
      .67-.21 2.2.82a7.65 7.65 0 0 1 2-.27 7.65 7.65 0 0 1 2 .27c1.53-1.04 2.2-.82
      2.2-.82.44 1.1.16 1.91.08 2.11.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65
      3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.001
      8.001 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
      </svg>
        GitHub
      <% end %>
      </div>
    <% end %>
  </div>
<% end %> 